### ISSUE TITLE
Use fuzzy matching

### ISSUE THREAD

**Issue by AntiCompositeNumber** [AntiCompositeNumber/iNaturalistReviewer#21]
Fuzzy matching using SSIM scores via pyssim was implemented and runs fine locally. However, pyssim is extremely slow on Toolforge, making it unusable. It also used a significant amount of memory, crashing the pod. SSIM matching was disabled in the configuration.

- [ ] ~~Investigate why pyssim is slow on Toolforge~~
- [ ] ~~Fix those issues and re-enable pyssim~~
or
- [x] Investigate replacement fuzzy matching libraries
- [ ] Test performance & determine optimal configuration for high-confidence matching
- [ ] Replace pyssim

**Comment by mdaniels5757** [comment]
You may find my primitive approach in [mdaniels5757/MDanielsBot-FinnaReviewer/CheckFinna.py#L106](https://github.com/mdaniels5757/MDanielsBot-FinnaReviewer/blob/master/CheckFinna.py#L106) using PIL (`from PIL import Image`) helpful. Note that the ideal threshold (`diffPercent`) would probably be different for the images you review (mine was max 9% difference).

**Comment by AntiCompositeNumber** [comment]
I'm probably going to go with the perceptual hash algorithm, which has a good implementation in https://pypi.org/project/ImageHash/. It's fairly quick, even on Toolforge (I tested it this time). It's also better optimized for the one-to-many comparisons that iNaturalistBot has to do because of iNat's data structure. 

I generally see four types of modifications to images: scaling, minor crop, major crop, and changes to brightness & contrast. phash seems to do well in everything but major crops.

ImageHash uses a Hamming distance metric for image similarity/difference, instead of the percentage in SSIM or pixel difference. Using a maximum Hamming distance of about 4 seems to be common, but I wasn't able to find great data about Hamming distance for crops of various sizes. My minimal testing indicates that dist < 4 is a safe starting point.

**Comment by AntiCompositeNumber** [comment]
![phash_hamming_hist](https://user-images.githubusercontent.com/10331574/88577267-bd2d3000-d014-11ea-886b-c58110fcf8e9.png)
